### PR TITLE
Replace nvim.Pipeline with nvim.Batch

### PR DESCRIPTION
**Pull request by ghost**
It looks like it's safe to replace nvim.Pipeline with nvim.Batch in nvim-go. If so, I'd like to make the switch and delete nvim.Pipeline from neovim/go-clent.  

This is a work in progress. I currently have this test failure:

```
 nvim-go/commands
--- FAIL: TestCommands_Fmt (0.01s)
    --- FAIL: TestCommands_Fmt/broken_(astdump) (0.01s)
    	fmt_test.go:78: "broken (astdump)". Commands.Fmt(/Users/gary/Desktop/nvim-go/src/nvim-go/testdata/go/src/broken), wantErr true
FAIL
FATAL: command "test" failed: [/var/folders/gm/4klryl254tq8kws1xsf8m9j40000gn/T/gb653988796/nvim-go/commands/testmain/_test/testmain]: exit status 1
```

### CODE REVIEW

**Comment by zchee** [comment]
@garyburd Wow, thanks for pull request!
I'll check it tonight.

**Comment by zchee** [comment]
@garyburd Hm, I tried **real** test with `Gofmt` command, but below's occur error:

```sh
(*Commands).Fmt: [1 args must be Array]
```

It does not occur on current `master` branch; I don't know why happened it...
I'll try more detailed debug it.

**Comment by garyburd** [comment]
Let me know if you would like me to debug the issue.

**Comment by zchee** [comment]
@garyburd Thanks, now quickly debugging, It's occur on below with `github.com/pkg/errors` error stacks:

```go
// Fmt format to the current buffer source uses gofmt behavior.
func (c *Commands) Fmt(dir string) interface{} {
	defer nvimutil.Profile(time.Now(), "GoFmt")
	defer c.ctx.SetContext(dir)()

	var (
		b nvim.Buffer
		w nvim.Window
	)
	c.Batch.CurrentBuffer(&b)
	c.Batch.CurrentWindow(&w)
	if err := c.Batch.Execute(); err != nil {
		return errors.WithStack(err) # this point
	}
.
.
.
```

Also, works fine `Gobuild` command, but not works `GoGuru***` command.
Hmm.... strange.

**Comment by zchee** [comment]
@garyburd I tried below change(yeah, just in case), works fine:

```go
func (c *Commands) Guru(args []string, eval *funcGuruEval) interface{} {
	defer nvimutil.Profile(time.Now(), "Guru")

	mode := args[0]
	if len(args) > 1 {
		return guruHelp(c.Nvim, mode)
	}

	dir := filepath.Dir(eval.File)
	defer c.ctx.SetContext(dir)()

	defer func() (err error) {
		if r := recover(); r != nil {
			err = errors.Errorf("guru internal panic.\nMaybe your set 'g:go#guru#reflection' to 1. Please retry with disable it option.\nOriginal panic message:\n\t%v", r.(error))
			return errors.WithStack(err)
		}
		return nil
	}()

	// === change point ===
	b, err := c.Nvim.CurrentBuffer()
	if err != nil {
		return errors.WithStack(err)
	}
	w, err := c.Nvim.CurrentWindow()
	if err != nil {
		return errors.WithStack(err)
	}
.
.
```

So, If `Batch` and `Pipeline` are can replace(same how to use) safer, I think it's caused by go-client internal.
What do you think about it?

**Comment by garyburd** [comment]
I agree that the issue may be in go-client.  I am investigating the issue.

**Comment by zchee** [comment]
@garyburd Thanks.
I read go-client test code, that passes related `Batch` test. But not testing `CurrentBuffer` API.
Also, In the my posted temporary `Guru` change, that's using `Batch` on after the `CurrentBuffer`:

```go
.
.
		// TODO(zchee): should change nvimutil.SplitPos behavior
		f := strings.Split(obj.ObjPos, ":")
		if f[0] != eval.File {
			c.Batch.Command(fmt.Sprintf("keepjumps edit %s", pathutil.Rel(eval.Cwd, fname)))
		}
		c.Batch.SetWindowCursor(w, [2]int{line, col - 1})
		if err := c.Batch.Execute(); err != nil {
			return nvimutil.ErrorWrap(c.Nvim, errors.WithStack(err))
		}
.
.
```

But works fine if change `c.Nvim.CurrentBuffer()`.
Maybe this issue only of `CurrentBuffer`...? So, it's Neovim's internal `atomic` API bugs...?

**Comment by zchee** [comment]
@garyburd Sorry noisy. That error message from the
https://github.com/neovim/neovim/blob/da6f4c146e2277a4ad7e7bab8a63aa4f4f262c18/src/nvim/api/vim.c#L763-L767

**Comment by garyburd** [comment]
I found the error on go-client.  Fix coming soon.

**Comment by zchee** [comment]
@garyburd Thanks!
I'll update go-client vendor to latest after fixed.

**Comment by garyburd** [comment]
I submitted the fix at https://github.com/neovim/go-client/commit/b6a9d8a7aa245088b61e91a4867c7dc963240c30.  Thank you for your help!

**Comment by zchee** [comment]
@garyburd Yes! works fine! Thanks quickly fix :)
I'll merge it. very thanks pull request, and
> I'd like to make the switch and delete nvim.Pipeline from neovim/go-clent.

Yeah, delete `Pipeline` is agreed. Sorry for the I'm blocker.

**Pull request merged**
